package com.printforge.printforge.fileservice.geometry;

import com.printforge.printforge.fileservice.geometry.GCodeWeightParser.GCodeResult;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Pure unit test, no Spring context or DB.
 *
 * Run with: ./mvnw test -Dtest=GCodeWeightParserTest
 */
class GCodeWeightParserTest {

    private final GCodeWeightParser parser = new GCodeWeightParser();

    private static byte[] bytes(String text) {
        return text.getBytes(StandardCharsets.UTF_8);
    }

    @Test
    void prusaWeightInGramsIsUsedDirectly() {
        String gcode = """
                ; generated by PrusaSlicer
                ; filament used [mm] = 4108.20
                ; filament used [g] = 12.34
                G28
                """;

        GCodeResult result = parser.parse(bytes(gcode), "test.gcode", "PLA");

        assertTrue(result.parseSucceeded());
        assertEquals(12.34, result.weightGrams(), 0.001,
                "a direct [g] value should be used as-is, not derived from the [mm] line even though both are present");
        assertNull(result.durationMinutes());
    }

    @Test
    void prusaWeightInMmConvertsToGramsUsingMaterialDensity() {
        String gcode = "; filament used [mm] = 4108.20\n";

        // radiusCm = (1.75/10)/2 = 0.0875; volumeCm3 = pi*0.0875^2*(4108.20/10) = pi*0.00765625*410.82
        double radiusCm = 0.0875;
        double expectedVolumeCm3 = Math.PI * radiusCm * radiusCm * (4108.20 / 10.0);
        double expectedGramsPla = expectedVolumeCm3 * 1.24;
        double expectedGramsResin = expectedVolumeCm3 * 1.10;

        GCodeResult plaResult = parser.parse(bytes(gcode), "test.gcode", "PLA");
        GCodeResult resinResult = parser.parse(bytes(gcode), "test.gcode", "RESIN");

        assertTrue(plaResult.parseSucceeded());
        assertEquals(expectedGramsPla, plaResult.weightGrams(), 0.001);

        assertTrue(resinResult.parseSucceeded());
        assertEquals(expectedGramsResin, resinResult.weightGrams(), 0.001);
        assertNotEquals(plaResult.weightGrams(), resinResult.weightGrams(),
                "different materials must produce different weights from the same filament length");
    }

    @Test
    void curaWeightInMetersConvertsToGrams() {
        String gcode = ";Filament used: 4.1m\n";

        double radiusCm = 0.0875;
        double lengthMm = 4.1 * 1000.0;
        double expectedVolumeCm3 = Math.PI * radiusCm * radiusCm * (lengthMm / 10.0);
        double expectedGrams = expectedVolumeCm3 * 1.24; // default PLA (no material passed)

        GCodeResult result = parser.parse(bytes(gcode), "test.gcode", null);

        assertTrue(result.parseSucceeded());
        assertEquals(expectedGrams, result.weightGrams(), 0.001);
    }

    @Test
    void prusaPrintTimeWithHoursMinutesSecondsConvertsToTotalMinutes() {
        String gcode = "; estimated printing time = 1h 23m 45s\n";

        GCodeResult result = parser.parse(bytes(gcode), "test.gcode", "PLA");

        assertTrue(result.parseSucceeded());
        assertEquals(60.0 + 23.0 + 45.0 / 60.0, result.durationMinutes(), 0.001);
        assertNull(result.weightGrams());
    }

    @Test
    void prusaPrintTimeWithOnlyMinutesAndSecondsConvertsCorrectly() {
        String gcode = "; estimated printing time = 23m 45s\n";

        GCodeResult result = parser.parse(bytes(gcode), "test.gcode", "PLA");

        assertTrue(result.parseSucceeded());
        assertEquals(23.0 + 45.0 / 60.0, result.durationMinutes(), 0.001);
    }

    @Test
    void curaTimeInSecondsConvertsToMinutes() {
        String gcode = ";TIME:5025\n";

        GCodeResult result = parser.parse(bytes(gcode), "test.gcode", "PLA");

        assertTrue(result.parseSucceeded());
        assertEquals(5025.0 / 60.0, result.durationMinutes(), 0.001);
        assertNull(result.weightGrams());
    }

    @Test
    void bothWeightAndTimeCanBeFoundInTheSameFile() {
        String gcode = """
                ; filament used [g] = 12.34
                ; estimated printing time = 1h 23m 45s
                """;

        GCodeResult result = parser.parse(bytes(gcode), "test.gcode", "PLA");

        assertTrue(result.parseSucceeded());
        assertEquals(12.34, result.weightGrams(), 0.001);
        assertEquals(60.0 + 23.0 + 45.0 / 60.0, result.durationMinutes(), 0.001);
    }

    @Test
    void noKnownPatternPresentFailsCleanly() {
        String gcode = """
                ; a gcode file from some other slicer
                G28
                G1 X10 Y10
                """;

        GCodeResult result = assertDoesNotThrow(
                () -> parser.parse(bytes(gcode), "unknown-slicer.gcode", "PLA"));

        assertFalse(result.parseSucceeded());
        assertNull(result.weightGrams());
        assertNull(result.durationMinutes());
    }

    @Test
    void emptyFileFailsCleanly() {
        GCodeResult result = assertDoesNotThrow(
                () -> parser.parse(new byte[0], "empty.gcode", "PLA"));

        assertFalse(result.parseSucceeded());
    }
}
