import { PrintJob, Material, Printer, Notification, User } from '../types';

export const MOCK_USER: User = {
  user_id: 'u1',
  full_name: 'John Yeboah',
  email: 'john.yeboah@knust.edu.gh',
  role: 'student',
};

export const MOCK_STAFF_USER: User = {
  user_id: 'u2',
  full_name: 'Dr. Ama Boateng',
  email: 'a.boateng@knust.edu.gh',
  role: 'lab_staff',
};

export const MOCK_ADMIN_USER: User = {
  user_id: 'u3',
  full_name: 'Prof. Kwame Asante',
  email: 'k.asante@knust.edu.gh',
  role: 'admin',
};

export const MOCK_JOBS: PrintJob[] = [
  {
    job_id: 'j001',
    user_id: 'u1',
    user_name: 'John Yeboah',
    file_name: 'gear_assembly_v3.stl',
    material: 'PLA',
    color: 'Black',
    quantity: 2,
    status: 'printing',
    submitted_at: '2026-06-15T08:30:00Z',
    estimated_cost: 45.50,
    estimated_time: 180,
    printer_name: 'Prusa MK4 — Bay A',
    queue_position: 1,
    notes: 'Please print with 20% infill',
  },
  {
    job_id: 'j002',
    user_id: 'u1',
    user_name: 'John Yeboah',
    file_name: 'bracket_final.stl',
    material: 'PETG',
    color: 'Clear',
    quantity: 1,
    status: 'approved',
    submitted_at: '2026-06-16T10:00:00Z',
    estimated_cost: 22.00,
    estimated_time: 95,
    queue_position: 3,
  },
  {
    job_id: 'j003',
    user_id: 'u1',
    user_name: 'John Yeboah',
    file_name: 'robot_chassis.stl',
    material: 'ABS',
    color: 'White',
    quantity: 1,
    status: 'submitted',
    submitted_at: '2026-06-17T14:20:00Z',
  },
  {
    job_id: 'j004',
    user_id: 'u1',
    user_name: 'John Yeboah',
    file_name: 'test_cube.stl',
    material: 'PLA',
    color: 'Red',
    quantity: 3,
    status: 'completed',
    submitted_at: '2026-06-10T09:00:00Z',
    estimated_cost: 15.75,
    estimated_time: 60,
    printer_name: 'Bambu Lab X1 — Bay B',
  },
  {
    job_id: 'j005',
    user_id: 'u1',
    user_name: 'John Yeboah',
    file_name: 'prototype_v1.stl',
    material: 'Resin',
    color: 'Grey',
    quantity: 1,
    status: 'rejected',
    submitted_at: '2026-06-12T11:15:00Z',
    notes: 'File has non-manifold geometry — please fix and resubmit.',
  },
  {
    job_id: 'j006',
    user_id: 'u4',
    user_name: 'Esi Mensah',
    file_name: 'turbine_blade.stl',
    material: 'PETG',
    color: 'Blue',
    quantity: 4,
    status: 'queued',
    submitted_at: '2026-06-17T08:00:00Z',
    estimated_cost: 88.00,
    estimated_time: 320,
    queue_position: 2,
  },
  {
    job_id: 'j007',
    user_id: 'u5',
    user_name: 'Kofi Acheampong',
    file_name: 'housing_enclosure.stl',
    material: 'ABS',
    color: 'Black',
    quantity: 1,
    status: 'submitted',
    submitted_at: '2026-06-18T07:45:00Z',
  },
];

export const MOCK_MATERIALS: Material[] = [
  {
    material_id: 'm1',
    material_name: 'PLA',
    colors: ['Black', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Orange'],
    cost_per_unit: 12.50,
    availability_status: 'available',
    description: 'Standard filament. Great for prototypes and general use.',
  },
  {
    material_id: 'm2',
    material_name: 'PETG',
    colors: ['Clear', 'Black', 'Blue', 'White'],
    cost_per_unit: 16.00,
    availability_status: 'available',
    description: 'Durable and slightly flexible. Good for functional parts.',
  },
  {
    material_id: 'm3',
    material_name: 'ABS',
    colors: ['Black', 'White', 'Grey'],
    cost_per_unit: 14.00,
    availability_status: 'low',
    description: 'Heat-resistant. Ideal for engineering applications.',
  },
  {
    material_id: 'm4',
    material_name: 'Resin',
    colors: ['Clear', 'Grey', 'White'],
    cost_per_unit: 28.00,
    availability_status: 'available',
    description: 'High detail SLA resin. Best for intricate models.',
  },
  {
    material_id: 'm5',
    material_name: 'TPU',
    colors: ['Black', 'White', 'Blue'],
    cost_per_unit: 20.00,
    availability_status: 'out_of_stock',
    description: 'Flexible filament for soft or rubber-like parts.',
  },
];

export const MOCK_PRINTERS: Printer[] = [
  {
    printer_id: 'p1',
    printer_name: 'Prusa MK4',
    printer_status: 'printing',
    lab_location: 'Bay A — Engineering Lab',
    current_job: 'gear_assembly_v3.stl',
  },
  {
    printer_id: 'p2',
    printer_name: 'Bambu Lab X1',
    printer_status: 'idle',
    lab_location: 'Bay B — Engineering Lab',
  },
  {
    printer_id: 'p3',
    printer_name: 'Creality Ender 5',
    printer_status: 'idle',
    lab_location: 'Bay C — Innovation Hub',
  },
  {
    printer_id: 'p4',
    printer_name: 'Formlabs Form 3',
    printer_status: 'maintenance',
    lab_location: 'Resin Lab — Room 204',
  },
  {
    printer_id: 'p5',
    printer_name: 'Ultimaker S5',
    printer_status: 'offline',
    lab_location: 'Bay D — Architecture Studio',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    notification_id: 'n1',
    message: 'Your job "gear_assembly_v3.stl" has started printing on Prusa MK4 — Bay A.',
    type: 'info',
    is_read: false,
    created_at: '2026-06-18T09:00:00Z',
    job_id: 'j001',
  },
  {
    notification_id: 'n2',
    message: 'Your job "bracket_final.stl" has been approved. It is now in queue position 3.',
    type: 'success',
    is_read: false,
    created_at: '2026-06-17T16:30:00Z',
    job_id: 'j002',
  },
  {
    notification_id: 'n3',
    message: 'Your job "prototype_v1.stl" was rejected. Reason: non-manifold geometry detected.',
    type: 'error',
    is_read: true,
    created_at: '2026-06-13T10:00:00Z',
    job_id: 'j005',
  },
  {
    notification_id: 'n4',
    message: 'Your job "test_cube.stl" is complete and ready for pickup at Bay B.',
    type: 'success',
    is_read: true,
    created_at: '2026-06-11T14:00:00Z',
    job_id: 'j004',
  },
];
